### ISSUE TITLE
实时检测延迟很大，正常吗？

### ISSUE THREAD

**Issue by lusihua** [XC-Li/DL_Final_Project_Group_1#6]

**Comment by XC-Li** [comment]
正常，因为实时检测没有用GPU。

**Comment by lusihua** [comment]
感谢你的回复，请问为什么实时检测的时候显存被占满了呢

**Comment by XC-Li** [comment]
这个情况我没有遇到，猜测可能是OpenCV的问题。
实时检查是先使用OpenCV的预训练人脸识别模型检测人脸，再用keras我训练的模型来预测表情的。
在我实验时，在没有人脸的情况下视频是流畅的，所以我认为延迟是由于keras用CPU进行预测导致的。
keras预测表情的代码在“Code/real_time_detection/RTD_helper.py” 中，
我建议可以将此行中的keras模型的返回结果改成一个固定值，例如“happiness, {}”，来排除keras的影响，看看是否是由于OpenCV导致了显存的问题：
https://github.com/XC-Li/Facial_Expression_Recognition/blob/6b7fadc3066688a3adba4a8e8a279a24611bb0af/Code/real_time_detection/RTD_V2.py#L38
